apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: es-local-storage
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  basePath: "/data/elasticsearch"
